Repository JuliaPackaging/BinaryBuilder.jl, pull requests merged in 2021-12, with the labels that each got.

#1121 Update BinaryBuilderBase to upgrade to Rust 1.57.1
  Manifest.toml
  Project.toml
  test/building.jl
Labels: toolchain :wrench: :chains:, rust :crab:

#1119 In `bb add`, unlink artifacts, but move rm to BBBase
  src/wizard/interactive_build.jl
  test/wizard.jl
Labels: wizard :mage:

#1122 [Docs] Suggest using release build type for Meson
  docs/src/build_tips.md
  src/wizard/hints.jl
Labels: documentation :book:

#1123 [Docs] Add installation tips about Rust and Go
  docs/src/build_tips.md
Labels: documentation :book:

#1126 [docs] explain use of Preferences.jl to override JLL
  docs/src/jll.md
Labels: documentation :book:

#1137 update dead link in documentation
  docs/src/FAQ.md
Labels: documentation :book:
